### ISSUE TITLE
failed with exit code 1120

### ISSUE THREAD

**Issue by saracenaly** [LabForComputationalVision/pyrtools#18] opened 2022-12-28 22:36 UTC
Hello,

I can not install the library with pip it gives me "failed with exit code 1120" error code.

**Comment by billbrod** [comment] 2023-01-03 16:16
Hmm, I am unable to reproduce your error, can you try installing `pyrtools` in a new virtual environment with python 3.7, 3.8, 3.9, or 3.10? If you continue to have problems, can you provide some more details on your system (what's your operating system, how did you install python and setup the virtual environment, etc) and the steps you took?

**Comment by freshNfunky** [comment] 2023-02-02 23:32
i had the same problem. It's obviously a Windows problem. Downloading pyrtools locally and applying this patch accordingly, fixed the problem: https://techoverflow.net/2022/01/23/how-to-fix-python-cffi-error-lnk2001-unresolved-external-symbol-pyinit__/

**Comment by freshNfunky** [comment] 2023-02-03 07:54
...Well it turned out, that patching the required method `PyInit_wrapConv` is not enough. This Function requires to return an object of the type: PyModuleDef. See: https://docs.python.org/3/extending/building.html

**Comment by billbrod** [comment] 2023-02-06 21:17
Hey @freshNfunky , thanks for looking into this. With your fork, I'm able to install the package from pip without any errors, but on import, I get the following:
<img width="850" alt="pyrtools1" src="https://user-images.githubusercontent.com/6338509/217089789-33272237-a119-4082-a88e-93b3a784b840.PNG">

and then when I try to call the Laplacian pyramid (which uses the c code), I get:
<img width="667" alt="pyrtools2" src="https://user-images.githubusercontent.com/6338509/217089854-fb20996f-5bbf-4318-8b31-0b2ea2d8124e.PNG">

But this is a different error than the one you mentioned above. Are you able to install from your fork directly?

**Comment by NicWickman** [comment] 2023-09-24 10:21
Thank you @freshNfunky for the first look at this. I have solved the issue for windows on my fork @ https://github.com/NicWickman/pyrtools

The solution to make methods visible through the compiled dll via `_declspec(dllexport)` in the new `windows.c` file and the header files.

I would submit a PR, but this won't compile on unix. A cross-platform solution using macros should be easy enough for someone who's familiar with them.

**Comment by billbrod** [comment] 2023-12-18 19:25
Hi all, thanks for bringing this to our attention and for your proposing some solutions. With pull request #27, we now have Windows support. If you have try installing the newest version of pyrtools (either from source or pip, version 1.0.3), it should now work!

I'm going to close this issue, but if someone gets this issue again on Windows, please re-open it.

**Closed by billbrod** 2023-12-18 19:25 UTC
